### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by mattp256** [CentralIllinoisRoboticsClub/temp_arduino_backup#2]
Although the name is currently "temp_arduino_backup", this actually appears to be the main storage location for Wheele's Arduino boards. Rename to be more indicative of this.

**Comment by mattp256** [comment]
@coderkarl, I went to rename the repo but realized I don't have permissions to do it. Could you rename when you get a chance? Should be a place to do that under the 'Settings' for the repo. Up to you on the name - I recommend wheele_arduino, or wheele_controls

**Comment by coderkarl** [comment]
I renamed the temp_arduino_backup repo to wheele_arduino_controls
